### ISSUE TITLE
日付管理テスト

### ISSUE THREAD

**Issue by yoshtanaka** [yoshtanaka/toraberu#5]
- [x] 8/19：お盆休み

- [x] 8/19：お墓参り

- [ ] 8/21：帰る

**Comment by Kojito81** [comment]
-[] ホンマかいな

**Comment by yoshtanaka** [comment]
- [ ] 即時反映が見える

**Comment by yoshtanaka** [comment]
これで会話できるな

**Comment by Kojito81** [comment]
-[ ] Again

**Comment by yoshtanaka** [comment]
previewの右のほうのボタン

**Comment by yoshtanaka** [comment]
add a task list

**Comment by Kojito81** [comment]
- [x] 全部スペースか

**Comment by yoshtanaka** [comment]
これでいけるかな？

**Comment by Kojito81** [comment]
- [x] フォー！！いける！いけるぜ！

**Comment by yoshtanaka** [comment]
やりづらそうであれば、タスク管理ツールでもよいと思うけど

**Comment by yoshtanaka** [comment]
<h1>テストh1</h1>

**Comment by Kojito81** [comment]
一覧だとチェックボックスが何分の何かもわかるんだな

**Comment by yoshtanaka** [comment]
本当だ

**Comment by Kojito81** [comment]
- [ ] 一旦これでいいんでないでしょうか

**Comment by yoshtanaka** [comment]
タスクを人にアサインできるのが良いな

**Comment by yoshtanaka** [comment]
もはやチャット用のissue作ってもよいレベル

**Comment by Kojito81** [comment]
ただ、一番最初に作ったコメントを編集しないとチェックボックスの数は変わらないね
あと、issueレベルでは人にアサインできるけど、チェックボックスレベルではアサインできなくない？

**Comment by yoshtanaka** [comment]
チェックボックスレベルでissueを別に作る想定

**Comment by Kojito81** [comment]
二重管理か、、、

**Comment by yoshtanaka** [comment]
その時、projectタブでtodo作成してからconvert to issueすると、進捗状況の把握できて良いと思う

**Comment by yoshtanaka** [comment]
つーか各issueに日付つけて全部projectに登録すれば良いのか？

**Comment by Kojito81** [comment]
また新しいの出てきたな、、ちょっとまだ追いついてない

**Comment by yoshtanaka** [comment]
動かしてみればすぐわかると思う

**Comment by yoshtanaka** [comment]
ちなみに、issueのopen/closeに合わせて、todo/in progress/doneのボードに勝手に動くように設定できるらしい

**Comment by Kojito81** [comment]
ハングアウトに戻ろう
これで会話は下までスクロールめんどくさくなってきた笑
